#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models.Operations
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Gray_GymManager")]
	public partial class OperationsModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProduct_Entry(Product_Entry instance);
    partial void UpdateProduct_Entry(Product_Entry instance);
    partial void DeleteProduct_Entry(Product_Entry instance);
    partial void InsertEntry(Entry instance);
    partial void UpdateEntry(Entry instance);
    partial void DeleteEntry(Entry instance);
    partial void InsertProduct_Sale(Product_Sale instance);
    partial void UpdateProduct_Sale(Product_Sale instance);
    partial void DeleteProduct_Sale(Product_Sale instance);
    partial void InsertField_Reservation(Field_Reservation instance);
    partial void UpdateField_Reservation(Field_Reservation instance);
    partial void DeleteField_Reservation(Field_Reservation instance);
    partial void InsertInvoice(Invoice instance);
    partial void UpdateInvoice(Invoice instance);
    partial void DeleteInvoice(Invoice instance);
    #endregion
		
		public OperationsModelDataContext() : 
				base(global::DAL.Properties.Settings.Default.Gray_GymManagerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OperationsModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperationsModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperationsModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperationsModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Product_Entry> Product_Entries
		{
			get
			{
				return this.GetTable<Product_Entry>();
			}
		}
		
		public System.Data.Linq.Table<Subscription_Entry> Subscription_Entries
		{
			get
			{
				return this.GetTable<Subscription_Entry>();
			}
		}
		
		public System.Data.Linq.Table<Entry> Entries
		{
			get
			{
				return this.GetTable<Entry>();
			}
		}
		
		public System.Data.Linq.Table<Product_Sale> Product_Sales
		{
			get
			{
				return this.GetTable<Product_Sale>();
			}
		}
		
		public System.Data.Linq.Table<Subscription> Subscriptions
		{
			get
			{
				return this.GetTable<Subscription>();
			}
		}
		
		public System.Data.Linq.Table<Field_Reservation> Field_Reservations
		{
			get
			{
				return this.GetTable<Field_Reservation>();
			}
		}
		
		public System.Data.Linq.Table<Invoice> Invoices
		{
			get
			{
				return this.GetTable<Invoice>();
			}
		}
		
		private void InsertSubscription_Entry(Subscription_Entry obj)
		{
			System.Nullable<int> p1 = obj.id;
			this.Subscription_Entries_Insert(ref p1, ((System.Nullable<int>)(obj.Subscription_id)), ((System.Nullable<System.DateTime>)(obj.EntryDate)), ((System.Nullable<int>)(obj.created_by)), ((System.Nullable<System.DateTime>)(obj.created_at)));
			obj.id = p1.GetValueOrDefault();
		}
		
		private void UpdateSubscription_Entry(Subscription_Entry obj)
		{
			this.Subscription_Entries_Update(((System.Nullable<int>)(obj.id)), ((System.Nullable<int>)(obj.Subscription_id)), ((System.Nullable<System.DateTime>)(obj.EntryDate)), ((System.Nullable<int>)(obj.updated_by)), ((System.Nullable<System.DateTime>)(obj.updated_at)));
		}
		
		private void DeleteSubscription_Entry(Subscription_Entry obj)
		{
			this.Subscription_Entries_Delete(((System.Nullable<int>)(obj.id)));
		}
		
		private void InsertSubscription(Subscription obj)
		{
			System.Nullable<int> p1 = obj.id;
			this.Subscriptions_Insert(ref p1, ((System.Nullable<int>)(obj.Subscription_Type_id)), ((System.Nullable<decimal>)(obj.Price)), ((System.Nullable<byte>)(obj.DiscountProcent)), ((System.Nullable<System.DateTime>)(obj.SubscriptionStartDate)), ((System.Nullable<System.DateTime>)(obj.SubscriptionEndDate)), ((System.Nullable<bool>)(obj.HasUnilimitedEntries)), ((System.Nullable<byte>)(obj.EntryNumber)), ((System.Nullable<byte>)(obj.RemainingEntries)), obj.Details, ((System.Nullable<int>)(obj.Client_id)), ((System.Nullable<int>)(obj.created_by)), ((System.Nullable<System.DateTime>)(obj.created_at)));
			obj.id = p1.GetValueOrDefault();
		}
		
		private void UpdateSubscription(Subscription obj)
		{
			this.Subscriptions_Update(((System.Nullable<int>)(obj.id)), ((System.Nullable<int>)(obj.Subscription_Type_id)), ((System.Nullable<decimal>)(obj.Price)), ((System.Nullable<byte>)(obj.DiscountProcent)), ((System.Nullable<System.DateTime>)(obj.SubscriptionStartDate)), ((System.Nullable<System.DateTime>)(obj.SubscriptionEndDate)), ((System.Nullable<bool>)(obj.HasUnilimitedEntries)), ((System.Nullable<byte>)(obj.EntryNumber)), ((System.Nullable<byte>)(obj.RemainingEntries)), obj.Details, ((System.Nullable<int>)(obj.Client_id)), ((System.Nullable<int>)(obj.updated_by)), ((System.Nullable<System.DateTime>)(obj.updated_at)));
		}
		
		private void DeleteSubscription(Subscription obj)
		{
			this.Subscriptions_Delete(((System.Nullable<int>)(obj.id)));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Entries_Delete")]
		public int Entries_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Field_Reservations_Delete")]
		public int Field_Reservations_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Product_Entries_Delete")]
		public int Product_Entries_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Product_Entries_Update")]
		public int Product_Entries_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product_id", DbType="Int")] System.Nullable<int> product_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductEntryDate", DbType="DateTime")] System.Nullable<System.DateTime> productEntryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryPrice", DbType="Money")] System.Nullable<decimal> entryPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryQuantity", DbType="Float")] System.Nullable<double> entryQuantity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> updated_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> updated_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, product_id, productEntryDate, entryPrice, entryQuantity, updated_by, updated_at);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Product_Entries_Insert")]
		public int Product_Entries_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product_id", DbType="Int")] System.Nullable<int> product_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductEntryDate", DbType="DateTime")] System.Nullable<System.DateTime> productEntryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryPrice", DbType="Money")] System.Nullable<decimal> entryPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryQuantity", DbType="Float")] System.Nullable<double> entryQuantity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> created_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> created_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, product_id, productEntryDate, entryPrice, entryQuantity, created_by, created_at);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Product_Sales_Delete")]
		public int Product_Sales_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Subscriptions_Delete")]
		public int Subscriptions_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Subscription_Entries_Delete")]
		public int Subscription_Entries_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Subscription_Entries_Insert")]
		public int Subscription_Entries_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Subscription_id", DbType="Int")] System.Nullable<int> subscription_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryDate", DbType="DateTime")] System.Nullable<System.DateTime> entryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> created_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> created_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, subscription_id, entryDate, created_by, created_at);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Subscription_Entries_Update")]
		public int Subscription_Entries_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Subscription_id", DbType="Int")] System.Nullable<int> subscription_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryDate", DbType="DateTime")] System.Nullable<System.DateTime> entryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> updated_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> updated_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, subscription_id, entryDate, updated_by, updated_at);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Entries_Insert")]
		public int Entries_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Entry_Type_id", DbType="Int")] System.Nullable<int> entry_Type_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryDate", DbType="DateTime")] System.Nullable<System.DateTime> entryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Money")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountProcent", DbType="TinyInt")] System.Nullable<byte> discountProcent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Details", DbType="VarChar(200)")] string details, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client_id", DbType="Int")] System.Nullable<int> client_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> created_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> created_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, entry_Type_id, entryDate, price, discountProcent, details, client_id, created_by, created_at);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Entries_Update")]
		public int Entries_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Entry_Type_id", DbType="Int")] System.Nullable<int> entry_Type_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryDate", DbType="DateTime")] System.Nullable<System.DateTime> entryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Money")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountProcent", DbType="TinyInt")] System.Nullable<byte> discountProcent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Details", DbType="VarChar(200)")] string details, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client_id", DbType="Int")] System.Nullable<int> client_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> updated_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> updated_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, entry_Type_id, entryDate, price, discountProcent, details, client_id, updated_by, updated_at);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Product_Sales_Insert")]
		public int Product_Sales_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product_id", DbType="Int")] System.Nullable<int> product_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductSalesDate", DbType="DateTime")] System.Nullable<System.DateTime> productSalesDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesPrice", DbType="Money")] System.Nullable<decimal> salesPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountProcent", DbType="TinyInt")] System.Nullable<byte> discountProcent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesQuantity", DbType="Float")] System.Nullable<double> salesQuantity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client_id", DbType="Int")] System.Nullable<int> client_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> created_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> created_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, product_id, productSalesDate, salesPrice, discountProcent, salesQuantity, client_id, created_by, created_at);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Product_Sales_Update")]
		public int Product_Sales_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Product_id", DbType="Int")] System.Nullable<int> product_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductSalesDate", DbType="DateTime")] System.Nullable<System.DateTime> productSalesDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesPrice", DbType="Money")] System.Nullable<decimal> salesPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountProcent", DbType="TinyInt")] System.Nullable<byte> discountProcent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SalesQuantity", DbType="Float")] System.Nullable<double> salesQuantity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client_id", DbType="Int")] System.Nullable<int> client_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> updated_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> updated_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, product_id, productSalesDate, salesPrice, discountProcent, salesQuantity, client_id, updated_by, updated_at);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Subscriptions_Insert")]
		public int Subscriptions_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Subscription_Type_id", DbType="Int")] System.Nullable<int> subscription_Type_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Money")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountProcent", DbType="TinyInt")] System.Nullable<byte> discountProcent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubscriptionStartDate", DbType="DateTime")] System.Nullable<System.DateTime> subscriptionStartDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubscriptionEndDate", DbType="DateTime")] System.Nullable<System.DateTime> subscriptionEndDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasUnilimitedEntries", DbType="Bit")] System.Nullable<bool> hasUnilimitedEntries, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryNumber", DbType="TinyInt")] System.Nullable<byte> entryNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RemainingEntries", DbType="TinyInt")] System.Nullable<byte> remainingEntries, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Details", DbType="VarChar(200)")] string details, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client_id", DbType="Int")] System.Nullable<int> client_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> created_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> created_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, subscription_Type_id, price, discountProcent, subscriptionStartDate, subscriptionEndDate, hasUnilimitedEntries, entryNumber, remainingEntries, details, client_id, created_by, created_at);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Subscriptions_Update")]
		public int Subscriptions_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Subscription_Type_id", DbType="Int")] System.Nullable<int> subscription_Type_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Money")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountProcent", DbType="TinyInt")] System.Nullable<byte> discountProcent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubscriptionStartDate", DbType="DateTime")] System.Nullable<System.DateTime> subscriptionStartDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubscriptionEndDate", DbType="DateTime")] System.Nullable<System.DateTime> subscriptionEndDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasUnilimitedEntries", DbType="Bit")] System.Nullable<bool> hasUnilimitedEntries, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryNumber", DbType="TinyInt")] System.Nullable<byte> entryNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RemainingEntries", DbType="TinyInt")] System.Nullable<byte> remainingEntries, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Details", DbType="VarChar(200)")] string details, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client_id", DbType="Int")] System.Nullable<int> client_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> updated_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> updated_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, subscription_Type_id, price, discountProcent, subscriptionStartDate, subscriptionEndDate, hasUnilimitedEntries, entryNumber, remainingEntries, details, client_id, updated_by, updated_at);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Subscriptions_GetActive")]
		public ISingleResult<Subscription> Subscriptions_GetActive()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Subscription>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Subscriptions_GetInactive")]
		public ISingleResult<Subscription> Subscriptions_GetInactive([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> startDateFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> startDateTo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDateFrom, startDateTo);
			return ((ISingleResult<Subscription>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Field_Reservations_Insert")]
		public int Field_Reservations_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Field_id", DbType="Int")] System.Nullable<int> field_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client_id", DbType="Int")] System.Nullable<int> client_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Money")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountProcent", DbType="TinyInt")] System.Nullable<byte> discountProcent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(200)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReservationFromDate", DbType="DateTime")] System.Nullable<System.DateTime> reservationFromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReservationToDate", DbType="DateTime")] System.Nullable<System.DateTime> reservationToDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Field_Reservation_Status_id", DbType="Int")] System.Nullable<int> field_Reservation_Status_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> created_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> created_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, field_id, client_id, price, discountProcent, description, reservationFromDate, reservationToDate, field_Reservation_Status_id, created_by, created_at);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Field_Reservations_Update")]
		public int Field_Reservations_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Field_id", DbType="Int")] System.Nullable<int> field_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client_id", DbType="Int")] System.Nullable<int> client_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Money")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiscountProcent", DbType="TinyInt")] System.Nullable<byte> discountProcent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(200)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReservationFromDate", DbType="DateTime")] System.Nullable<System.DateTime> reservationFromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReservationToDate", DbType="DateTime")] System.Nullable<System.DateTime> reservationToDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Field_Reservation_Status_id", DbType="Int")] System.Nullable<int> field_Reservation_Status_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> updated_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> updated_at)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, field_id, client_id, price, discountProcent, description, reservationFromDate, reservationToDate, field_Reservation_Status_id, updated_by, updated_at);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Invoices_GetInvoice")]
		public ISingleResult<Invoice> Invoices_GetInvoice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pClientId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pInvoiceYear, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pInvoiceMonth)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pClientId, pInvoiceYear, pInvoiceMonth);
			return ((ISingleResult<Invoice>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Invoices_Insert")]
		public int Invoices_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Client_id", DbType="Int")] System.Nullable<int> client_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceYear", DbType="Int")] System.Nullable<int> invoiceYear, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceMonth", DbType="Int")] System.Nullable<int> invoiceMonth, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceDay", DbType="Int")] System.Nullable<int> invoiceDay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, client_id, invoiceYear, invoiceMonth, invoiceDay);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Field_Reservations_UpdateStatusesJob")]
		public int Field_Reservations_UpdateStatusesJob()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="operations.Product_Entries")]
	public partial class Product_Entry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Product_id;
		
		private System.DateTime _ProductEntryDate;
		
		private decimal _EntryPrice;
		
		private double _EntryQuantity;
		
		private int _created_by;
		
		private System.DateTime _created_at;
		
		private System.Nullable<int> _updated_by;
		
		private System.Nullable<System.DateTime> _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnProduct_idChanging(int value);
    partial void OnProduct_idChanged();
    partial void OnProductEntryDateChanging(System.DateTime value);
    partial void OnProductEntryDateChanged();
    partial void OnEntryPriceChanging(decimal value);
    partial void OnEntryPriceChanged();
    partial void OnEntryQuantityChanging(double value);
    partial void OnEntryQuantityChanged();
    partial void Oncreated_byChanging(int value);
    partial void Oncreated_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_byChanging(System.Nullable<int> value);
    partial void Onupdated_byChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    #endregion
		
		public Product_Entry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_id", DbType="Int NOT NULL")]
		public int Product_id
		{
			get
			{
				return this._Product_id;
			}
			set
			{
				if ((this._Product_id != value))
				{
					this.OnProduct_idChanging(value);
					this.SendPropertyChanging();
					this._Product_id = value;
					this.SendPropertyChanged("Product_id");
					this.OnProduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductEntryDate", DbType="DateTime NOT NULL")]
		public System.DateTime ProductEntryDate
		{
			get
			{
				return this._ProductEntryDate;
			}
			set
			{
				if ((this._ProductEntryDate != value))
				{
					this.OnProductEntryDateChanging(value);
					this.SendPropertyChanging();
					this._ProductEntryDate = value;
					this.SendPropertyChanged("ProductEntryDate");
					this.OnProductEntryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryPrice", DbType="Money NOT NULL")]
		public decimal EntryPrice
		{
			get
			{
				return this._EntryPrice;
			}
			set
			{
				if ((this._EntryPrice != value))
				{
					this.OnEntryPriceChanging(value);
					this.SendPropertyChanging();
					this._EntryPrice = value;
					this.SendPropertyChanged("EntryPrice");
					this.OnEntryPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryQuantity", DbType="Float NOT NULL")]
		public double EntryQuantity
		{
			get
			{
				return this._EntryQuantity;
			}
			set
			{
				if ((this._EntryQuantity != value))
				{
					this.OnEntryQuantityChanging(value);
					this.SendPropertyChanging();
					this._EntryQuantity = value;
					this.SendPropertyChanged("EntryQuantity");
					this.OnEntryQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="Int NOT NULL")]
		public int created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_by", DbType="Int")]
		public System.Nullable<int> updated_by
		{
			get
			{
				return this._updated_by;
			}
			set
			{
				if ((this._updated_by != value))
				{
					this.Onupdated_byChanging(value);
					this.SendPropertyChanging();
					this._updated_by = value;
					this.SendPropertyChanged("updated_by");
					this.Onupdated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="operations.Subscription_Entries")]
	public partial class Subscription_Entry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Subscription_id;
		
		private System.DateTime _EntryDate;
		
		private int _created_by;
		
		private System.DateTime _created_at;
		
		private System.Nullable<int> _updated_by;
		
		private System.Nullable<System.DateTime> _updated_at;
		
		private EntityRef<Subscription> _Subscription;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnSubscription_idChanging(int value);
    partial void OnSubscription_idChanged();
    partial void OnEntryDateChanging(System.DateTime value);
    partial void OnEntryDateChanged();
    partial void Oncreated_byChanging(int value);
    partial void Oncreated_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_byChanging(System.Nullable<int> value);
    partial void Onupdated_byChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    #endregion
		
		public Subscription_Entry()
		{
			this._Subscription = default(EntityRef<Subscription>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subscription_id", DbType="Int NOT NULL")]
		public int Subscription_id
		{
			get
			{
				return this._Subscription_id;
			}
			set
			{
				if ((this._Subscription_id != value))
				{
					if (this._Subscription.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubscription_idChanging(value);
					this.SendPropertyChanging();
					this._Subscription_id = value;
					this.SendPropertyChanged("Subscription_id");
					this.OnSubscription_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime NOT NULL")]
		public System.DateTime EntryDate
		{
			get
			{
				return this._EntryDate;
			}
			set
			{
				if ((this._EntryDate != value))
				{
					this.OnEntryDateChanging(value);
					this.SendPropertyChanging();
					this._EntryDate = value;
					this.SendPropertyChanged("EntryDate");
					this.OnEntryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="Int NOT NULL")]
		public int created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_by", DbType="Int")]
		public System.Nullable<int> updated_by
		{
			get
			{
				return this._updated_by;
			}
			set
			{
				if ((this._updated_by != value))
				{
					this.Onupdated_byChanging(value);
					this.SendPropertyChanging();
					this._updated_by = value;
					this.SendPropertyChanged("updated_by");
					this.Onupdated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Subscription_Subscription_Entry", Storage="_Subscription", ThisKey="Subscription_id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Subscription Subscription
		{
			get
			{
				return this._Subscription.Entity;
			}
			set
			{
				Subscription previousValue = this._Subscription.Entity;
				if (((previousValue != value) 
							|| (this._Subscription.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Subscription.Entity = null;
						previousValue.Subscription_Entries.Remove(this);
					}
					this._Subscription.Entity = value;
					if ((value != null))
					{
						value.Subscription_Entries.Add(this);
						this._Subscription_id = value.id;
					}
					else
					{
						this._Subscription_id = default(int);
					}
					this.SendPropertyChanged("Subscription");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="operations.Entries")]
	public partial class Entry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Entry_Type_id;
		
		private System.DateTime _EntryDate;
		
		private decimal _Price;
		
		private byte _DiscountProcent;
		
		private string _Details;
		
		private int _Client_id;
		
		private int _created_by;
		
		private System.DateTime _created_at;
		
		private System.Nullable<int> _updated_by;
		
		private System.Nullable<System.DateTime> _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnEntry_Type_idChanging(int value);
    partial void OnEntry_Type_idChanged();
    partial void OnEntryDateChanging(System.DateTime value);
    partial void OnEntryDateChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnDiscountProcentChanging(byte value);
    partial void OnDiscountProcentChanged();
    partial void OnDetailsChanging(string value);
    partial void OnDetailsChanged();
    partial void OnClient_idChanging(int value);
    partial void OnClient_idChanged();
    partial void Oncreated_byChanging(int value);
    partial void Oncreated_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_byChanging(System.Nullable<int> value);
    partial void Onupdated_byChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    #endregion
		
		public Entry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Type_id", DbType="Int NOT NULL")]
		public int Entry_Type_id
		{
			get
			{
				return this._Entry_Type_id;
			}
			set
			{
				if ((this._Entry_Type_id != value))
				{
					this.OnEntry_Type_idChanging(value);
					this.SendPropertyChanging();
					this._Entry_Type_id = value;
					this.SendPropertyChanged("Entry_Type_id");
					this.OnEntry_Type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime NOT NULL")]
		public System.DateTime EntryDate
		{
			get
			{
				return this._EntryDate;
			}
			set
			{
				if ((this._EntryDate != value))
				{
					this.OnEntryDateChanging(value);
					this.SendPropertyChanging();
					this._EntryDate = value;
					this.SendPropertyChanged("EntryDate");
					this.OnEntryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountProcent", DbType="TinyInt NOT NULL")]
		public byte DiscountProcent
		{
			get
			{
				return this._DiscountProcent;
			}
			set
			{
				if ((this._DiscountProcent != value))
				{
					this.OnDiscountProcentChanging(value);
					this.SendPropertyChanging();
					this._DiscountProcent = value;
					this.SendPropertyChanged("DiscountProcent");
					this.OnDiscountProcentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details", DbType="VarChar(200)")]
		public string Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				if ((this._Details != value))
				{
					this.OnDetailsChanging(value);
					this.SendPropertyChanging();
					this._Details = value;
					this.SendPropertyChanged("Details");
					this.OnDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_id", DbType="Int NOT NULL")]
		public int Client_id
		{
			get
			{
				return this._Client_id;
			}
			set
			{
				if ((this._Client_id != value))
				{
					this.OnClient_idChanging(value);
					this.SendPropertyChanging();
					this._Client_id = value;
					this.SendPropertyChanged("Client_id");
					this.OnClient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="Int NOT NULL")]
		public int created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_by", DbType="Int")]
		public System.Nullable<int> updated_by
		{
			get
			{
				return this._updated_by;
			}
			set
			{
				if ((this._updated_by != value))
				{
					this.Onupdated_byChanging(value);
					this.SendPropertyChanging();
					this._updated_by = value;
					this.SendPropertyChanged("updated_by");
					this.Onupdated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="operations.Product_Sales")]
	public partial class Product_Sale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Product_id;
		
		private System.DateTime _ProductSalesDate;
		
		private decimal _SalesPrice;
		
		private double _SalesQuantity;
		
		private byte _DiscountProcent;
		
		private int _Client_id;
		
		private int _created_by;
		
		private System.DateTime _created_at;
		
		private System.Nullable<int> _updated_by;
		
		private System.Nullable<System.DateTime> _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnProduct_idChanging(int value);
    partial void OnProduct_idChanged();
    partial void OnProductSalesDateChanging(System.DateTime value);
    partial void OnProductSalesDateChanged();
    partial void OnSalesPriceChanging(decimal value);
    partial void OnSalesPriceChanged();
    partial void OnSalesQuantityChanging(double value);
    partial void OnSalesQuantityChanged();
    partial void OnDiscountProcentChanging(byte value);
    partial void OnDiscountProcentChanged();
    partial void OnClient_idChanging(int value);
    partial void OnClient_idChanged();
    partial void Oncreated_byChanging(int value);
    partial void Oncreated_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_byChanging(System.Nullable<int> value);
    partial void Onupdated_byChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    #endregion
		
		public Product_Sale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_id", DbType="Int NOT NULL")]
		public int Product_id
		{
			get
			{
				return this._Product_id;
			}
			set
			{
				if ((this._Product_id != value))
				{
					this.OnProduct_idChanging(value);
					this.SendPropertyChanging();
					this._Product_id = value;
					this.SendPropertyChanged("Product_id");
					this.OnProduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSalesDate", DbType="DateTime NOT NULL")]
		public System.DateTime ProductSalesDate
		{
			get
			{
				return this._ProductSalesDate;
			}
			set
			{
				if ((this._ProductSalesDate != value))
				{
					this.OnProductSalesDateChanging(value);
					this.SendPropertyChanging();
					this._ProductSalesDate = value;
					this.SendPropertyChanged("ProductSalesDate");
					this.OnProductSalesDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesPrice", DbType="Money NOT NULL")]
		public decimal SalesPrice
		{
			get
			{
				return this._SalesPrice;
			}
			set
			{
				if ((this._SalesPrice != value))
				{
					this.OnSalesPriceChanging(value);
					this.SendPropertyChanging();
					this._SalesPrice = value;
					this.SendPropertyChanged("SalesPrice");
					this.OnSalesPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesQuantity", DbType="Float NOT NULL")]
		public double SalesQuantity
		{
			get
			{
				return this._SalesQuantity;
			}
			set
			{
				if ((this._SalesQuantity != value))
				{
					this.OnSalesQuantityChanging(value);
					this.SendPropertyChanging();
					this._SalesQuantity = value;
					this.SendPropertyChanged("SalesQuantity");
					this.OnSalesQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountProcent", DbType="TinyInt NOT NULL")]
		public byte DiscountProcent
		{
			get
			{
				return this._DiscountProcent;
			}
			set
			{
				if ((this._DiscountProcent != value))
				{
					this.OnDiscountProcentChanging(value);
					this.SendPropertyChanging();
					this._DiscountProcent = value;
					this.SendPropertyChanged("DiscountProcent");
					this.OnDiscountProcentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_id", DbType="Int NOT NULL")]
		public int Client_id
		{
			get
			{
				return this._Client_id;
			}
			set
			{
				if ((this._Client_id != value))
				{
					this.OnClient_idChanging(value);
					this.SendPropertyChanging();
					this._Client_id = value;
					this.SendPropertyChanged("Client_id");
					this.OnClient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="Int NOT NULL")]
		public int created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_by", DbType="Int")]
		public System.Nullable<int> updated_by
		{
			get
			{
				return this._updated_by;
			}
			set
			{
				if ((this._updated_by != value))
				{
					this.Onupdated_byChanging(value);
					this.SendPropertyChanging();
					this._updated_by = value;
					this.SendPropertyChanged("updated_by");
					this.Onupdated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="operations.Subscriptions")]
	public partial class Subscription : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Subscription_Type_id;
		
		private decimal _Price;
		
		private byte _DiscountProcent;
		
		private System.DateTime _SubscriptionStartDate;
		
		private System.DateTime _SubscriptionEndDate;
		
		private bool _HasUnilimitedEntries;
		
		private System.Nullable<byte> _EntryNumber;
		
		private System.Nullable<byte> _RemainingEntries;
		
		private string _Details;
		
		private int _Client_id;
		
		private int _created_by;
		
		private System.DateTime _created_at;
		
		private System.Nullable<int> _updated_by;
		
		private System.Nullable<System.DateTime> _updated_at;
		
		private EntitySet<Subscription_Entry> _Subscription_Entries;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnSubscription_Type_idChanging(int value);
    partial void OnSubscription_Type_idChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnDiscountProcentChanging(byte value);
    partial void OnDiscountProcentChanged();
    partial void OnSubscriptionStartDateChanging(System.DateTime value);
    partial void OnSubscriptionStartDateChanged();
    partial void OnSubscriptionEndDateChanging(System.DateTime value);
    partial void OnSubscriptionEndDateChanged();
    partial void OnHasUnilimitedEntriesChanging(bool value);
    partial void OnHasUnilimitedEntriesChanged();
    partial void OnEntryNumberChanging(System.Nullable<byte> value);
    partial void OnEntryNumberChanged();
    partial void OnRemainingEntriesChanging(System.Nullable<byte> value);
    partial void OnRemainingEntriesChanged();
    partial void OnDetailsChanging(string value);
    partial void OnDetailsChanged();
    partial void OnClient_idChanging(int value);
    partial void OnClient_idChanged();
    partial void Oncreated_byChanging(int value);
    partial void Oncreated_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_byChanging(System.Nullable<int> value);
    partial void Onupdated_byChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    #endregion
		
		public Subscription()
		{
			this._Subscription_Entries = new EntitySet<Subscription_Entry>(new Action<Subscription_Entry>(this.attach_Subscription_Entries), new Action<Subscription_Entry>(this.detach_Subscription_Entries));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subscription_Type_id", DbType="Int NOT NULL")]
		public int Subscription_Type_id
		{
			get
			{
				return this._Subscription_Type_id;
			}
			set
			{
				if ((this._Subscription_Type_id != value))
				{
					this.OnSubscription_Type_idChanging(value);
					this.SendPropertyChanging();
					this._Subscription_Type_id = value;
					this.SendPropertyChanged("Subscription_Type_id");
					this.OnSubscription_Type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountProcent", DbType="TinyInt NOT NULL")]
		public byte DiscountProcent
		{
			get
			{
				return this._DiscountProcent;
			}
			set
			{
				if ((this._DiscountProcent != value))
				{
					this.OnDiscountProcentChanging(value);
					this.SendPropertyChanging();
					this._DiscountProcent = value;
					this.SendPropertyChanged("DiscountProcent");
					this.OnDiscountProcentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionStartDate", DbType="DateTime NOT NULL")]
		public System.DateTime SubscriptionStartDate
		{
			get
			{
				return this._SubscriptionStartDate;
			}
			set
			{
				if ((this._SubscriptionStartDate != value))
				{
					this.OnSubscriptionStartDateChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionStartDate = value;
					this.SendPropertyChanged("SubscriptionStartDate");
					this.OnSubscriptionStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionEndDate", DbType="DateTime NOT NULL")]
		public System.DateTime SubscriptionEndDate
		{
			get
			{
				return this._SubscriptionEndDate;
			}
			set
			{
				if ((this._SubscriptionEndDate != value))
				{
					this.OnSubscriptionEndDateChanging(value);
					this.SendPropertyChanging();
					this._SubscriptionEndDate = value;
					this.SendPropertyChanged("SubscriptionEndDate");
					this.OnSubscriptionEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasUnilimitedEntries", DbType="Bit NOT NULL")]
		public bool HasUnilimitedEntries
		{
			get
			{
				return this._HasUnilimitedEntries;
			}
			set
			{
				if ((this._HasUnilimitedEntries != value))
				{
					this.OnHasUnilimitedEntriesChanging(value);
					this.SendPropertyChanging();
					this._HasUnilimitedEntries = value;
					this.SendPropertyChanged("HasUnilimitedEntries");
					this.OnHasUnilimitedEntriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryNumber", DbType="TinyInt")]
		public System.Nullable<byte> EntryNumber
		{
			get
			{
				return this._EntryNumber;
			}
			set
			{
				if ((this._EntryNumber != value))
				{
					this.OnEntryNumberChanging(value);
					this.SendPropertyChanging();
					this._EntryNumber = value;
					this.SendPropertyChanged("EntryNumber");
					this.OnEntryNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainingEntries", DbType="TinyInt")]
		public System.Nullable<byte> RemainingEntries
		{
			get
			{
				return this._RemainingEntries;
			}
			set
			{
				if ((this._RemainingEntries != value))
				{
					this.OnRemainingEntriesChanging(value);
					this.SendPropertyChanging();
					this._RemainingEntries = value;
					this.SendPropertyChanged("RemainingEntries");
					this.OnRemainingEntriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details", DbType="VarChar(200)")]
		public string Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				if ((this._Details != value))
				{
					this.OnDetailsChanging(value);
					this.SendPropertyChanging();
					this._Details = value;
					this.SendPropertyChanged("Details");
					this.OnDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_id", DbType="Int NOT NULL")]
		public int Client_id
		{
			get
			{
				return this._Client_id;
			}
			set
			{
				if ((this._Client_id != value))
				{
					this.OnClient_idChanging(value);
					this.SendPropertyChanging();
					this._Client_id = value;
					this.SendPropertyChanged("Client_id");
					this.OnClient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="Int NOT NULL")]
		public int created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_by", DbType="Int")]
		public System.Nullable<int> updated_by
		{
			get
			{
				return this._updated_by;
			}
			set
			{
				if ((this._updated_by != value))
				{
					this.Onupdated_byChanging(value);
					this.SendPropertyChanging();
					this._updated_by = value;
					this.SendPropertyChanged("updated_by");
					this.Onupdated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Subscription_Subscription_Entry", Storage="_Subscription_Entries", ThisKey="id", OtherKey="Subscription_id")]
		public EntitySet<Subscription_Entry> Subscription_Entries
		{
			get
			{
				return this._Subscription_Entries;
			}
			set
			{
				this._Subscription_Entries.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Subscription_Entries(Subscription_Entry entity)
		{
			this.SendPropertyChanging();
			entity.Subscription = this;
		}
		
		private void detach_Subscription_Entries(Subscription_Entry entity)
		{
			this.SendPropertyChanging();
			entity.Subscription = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="operations.Field_Reservations")]
	public partial class Field_Reservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Field_id;
		
		private int _Client_id;
		
		private decimal _Price;
		
		private byte _DiscountProcent;
		
		private string _Description;
		
		private System.DateTime _ReservationFromDate;
		
		private System.DateTime _ReservationToDate;
		
		private int _Field_Reservation_Status_id;
		
		private int _created_by;
		
		private System.DateTime _created_at;
		
		private System.Nullable<int> _updated_by;
		
		private System.Nullable<System.DateTime> _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnField_idChanging(int value);
    partial void OnField_idChanged();
    partial void OnClient_idChanging(int value);
    partial void OnClient_idChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnDiscountProcentChanging(byte value);
    partial void OnDiscountProcentChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnReservationFromDateChanging(System.DateTime value);
    partial void OnReservationFromDateChanged();
    partial void OnReservationToDateChanging(System.DateTime value);
    partial void OnReservationToDateChanged();
    partial void OnField_Reservation_Status_idChanging(int value);
    partial void OnField_Reservation_Status_idChanged();
    partial void Oncreated_byChanging(int value);
    partial void Oncreated_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_byChanging(System.Nullable<int> value);
    partial void Onupdated_byChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    #endregion
		
		public Field_Reservation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field_id", DbType="Int NOT NULL")]
		public int Field_id
		{
			get
			{
				return this._Field_id;
			}
			set
			{
				if ((this._Field_id != value))
				{
					this.OnField_idChanging(value);
					this.SendPropertyChanging();
					this._Field_id = value;
					this.SendPropertyChanged("Field_id");
					this.OnField_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_id", DbType="Int NOT NULL")]
		public int Client_id
		{
			get
			{
				return this._Client_id;
			}
			set
			{
				if ((this._Client_id != value))
				{
					this.OnClient_idChanging(value);
					this.SendPropertyChanging();
					this._Client_id = value;
					this.SendPropertyChanged("Client_id");
					this.OnClient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountProcent", DbType="TinyInt NOT NULL")]
		public byte DiscountProcent
		{
			get
			{
				return this._DiscountProcent;
			}
			set
			{
				if ((this._DiscountProcent != value))
				{
					this.OnDiscountProcentChanging(value);
					this.SendPropertyChanging();
					this._DiscountProcent = value;
					this.SendPropertyChanged("DiscountProcent");
					this.OnDiscountProcentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationFromDate", DbType="DateTime NOT NULL")]
		public System.DateTime ReservationFromDate
		{
			get
			{
				return this._ReservationFromDate;
			}
			set
			{
				if ((this._ReservationFromDate != value))
				{
					this.OnReservationFromDateChanging(value);
					this.SendPropertyChanging();
					this._ReservationFromDate = value;
					this.SendPropertyChanged("ReservationFromDate");
					this.OnReservationFromDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationToDate", DbType="DateTime NOT NULL")]
		public System.DateTime ReservationToDate
		{
			get
			{
				return this._ReservationToDate;
			}
			set
			{
				if ((this._ReservationToDate != value))
				{
					this.OnReservationToDateChanging(value);
					this.SendPropertyChanging();
					this._ReservationToDate = value;
					this.SendPropertyChanged("ReservationToDate");
					this.OnReservationToDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Field_Reservation_Status_id", DbType="Int NOT NULL")]
		public int Field_Reservation_Status_id
		{
			get
			{
				return this._Field_Reservation_Status_id;
			}
			set
			{
				if ((this._Field_Reservation_Status_id != value))
				{
					this.OnField_Reservation_Status_idChanging(value);
					this.SendPropertyChanging();
					this._Field_Reservation_Status_id = value;
					this.SendPropertyChanged("Field_Reservation_Status_id");
					this.OnField_Reservation_Status_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="Int NOT NULL")]
		public int created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_by", DbType="Int")]
		public System.Nullable<int> updated_by
		{
			get
			{
				return this._updated_by;
			}
			set
			{
				if ((this._updated_by != value))
				{
					this.Onupdated_byChanging(value);
					this.SendPropertyChanging();
					this._updated_by = value;
					this.SendPropertyChanged("updated_by");
					this.Onupdated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="operations.Invoices")]
	public partial class Invoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Client_id;
		
		private int _InvoiceYear;
		
		private int _InvoiceMonth;
		
		private int _InvoiceDay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnClient_idChanging(int value);
    partial void OnClient_idChanged();
    partial void OnInvoiceYearChanging(int value);
    partial void OnInvoiceYearChanged();
    partial void OnInvoiceMonthChanging(int value);
    partial void OnInvoiceMonthChanged();
    partial void OnInvoiceDayChanging(int value);
    partial void OnInvoiceDayChanged();
    #endregion
		
		public Invoice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_id", DbType="Int NOT NULL")]
		public int Client_id
		{
			get
			{
				return this._Client_id;
			}
			set
			{
				if ((this._Client_id != value))
				{
					this.OnClient_idChanging(value);
					this.SendPropertyChanging();
					this._Client_id = value;
					this.SendPropertyChanged("Client_id");
					this.OnClient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceYear", DbType="Int NOT NULL")]
		public int InvoiceYear
		{
			get
			{
				return this._InvoiceYear;
			}
			set
			{
				if ((this._InvoiceYear != value))
				{
					this.OnInvoiceYearChanging(value);
					this.SendPropertyChanging();
					this._InvoiceYear = value;
					this.SendPropertyChanged("InvoiceYear");
					this.OnInvoiceYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceMonth", DbType="Int NOT NULL")]
		public int InvoiceMonth
		{
			get
			{
				return this._InvoiceMonth;
			}
			set
			{
				if ((this._InvoiceMonth != value))
				{
					this.OnInvoiceMonthChanging(value);
					this.SendPropertyChanging();
					this._InvoiceMonth = value;
					this.SendPropertyChanged("InvoiceMonth");
					this.OnInvoiceMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDay", DbType="Int NOT NULL")]
		public int InvoiceDay
		{
			get
			{
				return this._InvoiceDay;
			}
			set
			{
				if ((this._InvoiceDay != value))
				{
					this.OnInvoiceDayChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDay = value;
					this.SendPropertyChanged("InvoiceDay");
					this.OnInvoiceDayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
